# Generated by Django 3.1.1 on 2020-09-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_chat_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thread.chat'),
        ),
    ]
